### ISSUE TITLE
Polyfill error while imageKit setup

### ISSUE THREAD

**Issue by shubhamkashyapdev** [novanda1/payload-imagekit#1]
![imagekit_polyfill_error](https://user-images.githubusercontent.com/68468708/196050971-4cbc874b-bfbb-4379-9b50-af214441f75c.png)

Github Link: https://github.com/shubhamwebdesign/devstack_project_crm/tree/imagekit

I'm trying to setup imageKit with my payload app but it's giving me some polyfill errors.

https://payloadcms.com/docs/admin/webpack#aliasing-server-only-modules

**Comment by itsyashsahu** [comment]
Hii did you found a solution for this error i am facing the same issue

**Comment by novanda1** [comment]
Hi guys! You need to install [Imagekit](https://www.npmjs.com/package/imagekit)

**Comment by novanda1** [comment]
The installation documentation is updated.   
I'll close this, feel free to re-open it if you still encounter an error.

**Comment by novanda1** [comment]
Hi, thanks for reporting the issue. It's patched on the latest version. Thanks!
