### ISSUE TITLE
0.2.5 seems broken

### ISSUE THREAD

**Issue by zanami** [novanda1/payload-imagekit#2]
can't make it work
yarn add payloadcms-plugin-imagekit installs 0.2.5 in which there's no "dist" folder, hence "module not found" error 

changing version to 0.2.4 helps

see here 0.2.5 vs 0.2.4
https://www.npmjs.com/package/payloadcms-plugin-imagekit/v/0.2.5?activeTab=code
https://www.npmjs.com/package/payloadcms-plugin-imagekit/v/0.2.4?activeTab=code

**Comment by novanda1** [comment]
Thanks for report, it now fixed in latest version 

checkout here
https://www.npmjs.com/package/payloadcms-plugin-imagekit/v/0.3.0?
