### ISSUE TITLE
Incompatibility with Payload Cloud (and/or hosted latest Payload version)

### ISSUE THREAD

**Issue by damnsamn** [novanda1/payload-imagekit#4]
Issue
---
This plugin currently works perfectly in dev as of the latest Payload version - but doesn't function when hosted (at least on Payload Cloud).

Any new file uploaded will throw an error message on Save, "Something went wrong" with no additional context:
<img width="1170" alt="image" src="https://github.com/novanda1/payload-imagekit/assets/17864782/a4672bd1-d60d-4716-97f6-9565c2d9abc7">

Steps To Reproduce
---
1. Create a blank Payload project via `npx create-payload-app@latest`
2. Install `payloadcms-plugin-imagekit`
3. Configure a Media upload collection
4. Configure the plugin via `payload.config.ts`
   - At this point, it should function perfectly when running locally, correctly uploading images to ImageKit and returning the correct data
5. Host the project (in this case using a Payload Cloud free trial)
   - Ensure environment variables are correctly configured on the server
6. Once running - any media uploads will now break as described in the issue above

Minimal Reproduction Example
---
https://github.com/damnsamn/payload-imagekit-bug

This repo was created using the steps to reproduce above

**Comment by novanda1** [comment]
Hey, thanks for the report.

I tried to reproduce the bug and got the same error, "Something went wrong." Then I remembered that my country has a problem accessing Digital Ocean, and Payload CMS Cloud uses Digital Ocean. So, I tried turning on my VPN (France), hit the save button again, and it worked.

To make sure it only happens in Payload CMS Cloud/Digital Ocean, I tried deploying it on Northflank, and it worked without VPN.


**Payload CMS Cloud using VPN (France)** :
<img width="1059" alt="Screenshot 2024-01-11 at 12 21 07 PM" src="https://github.com/novanda1/payload-imagekit/assets/57532279/55bccfde-4acd-43ff-8d28-61c059a0a47b">

Northflank without VPN :
<img width="1079" alt="Screenshot 2024-01-11 at 11 59 34 AM" src="https://github.com/novanda1/payload-imagekit/assets/57532279/15743197-640a-4ca8-a548-8a84e5dcd505">

**Comment by damnsamn** [comment]
Thanks for that Novanda. I live in Australia (which as far as I know has no restrictions re: Digital Ocean). Are you suggesting this is a Payload Cloud issue? Will be happy to raise it with them if so

**Comment by novanda1** [comment]
I think the error came from the [cloud storage plugin](https://github.com/payloadcms/plugin-cloud-storage); I tried to comment out  [this line](https://github.com/damnsamn/payload-imagekit-bug/blob/1a860d87ceaff64e2133508155a7aa6223f5eb7c/src/payload.config.ts#L26C18-L26C18) and the error is gone.

**Comment by damnsamn** [comment]
Good catch! It looks like the Payload Cloud default file storage configuration conflicts with this package - which is probably to be expected 🤦

In order to function correctly on Payload Cloud, users will need to disable storage in the config, like so in `payload.config.js`:

```js
// ...
plugins: [
  payloadCloud({
    storage: false, // Disable file storage
  }),
  imagekitPlugin({ /* ... */ })
],
// ...
```

I think an update to this project's README is all that's necessary here.
