### ISSUE TITLE
Image Tags or Custom Folders

### ISSUE THREAD

**Issue by Bradleykingz** [novanda1/payload-imagekit#6]
First of all, thank you for the amazing library. It works perfectly.

For some background on my use-case - I have implemented a multi-tenant website with PayloadCMS, and would like a way to identify which image belongs to which user once they have been uploaded onto ImageKit.

Ideally, this would involve storing the images in different folders, depending on the user that uploaded them. Otherwise, setting a custom tag with the tenant's id on the image would be equally helpful.

Not sure how I would go about that?

**Comment by novanda1** [comment]
Hey @Bradleykingz,

Thanks for bringing this up!

I've just added a new feature to this library that allows you to customize the folder configuration for uploaded images in ImageKit. This means you can now organize images based on user or tenant ID (if you include the tenant ID on the request), which is perfect for your multi-tenant website setup.

Here's how it works:

```ts
const imagekitPlugin: Plugin = imagekitPlugin({
  config: {
    ...
  },
  collections: {
    media: {
      uploadOption: {
         // now the folder option is accept string or function with param PayloadRequest
         folder: (req) => {
            const userId = req.user.id; // Extract user ID from the request object
            return `${userId}-images`; // Set the folder based on the user ID
         }
        ...
      },
    ...
    },
  },
});
```

This snippet dynamically sets the folder name based on the user ID extracted from the request object.

Feel free to give it a try in your project, and let me know if you run into any issues or have any feedback. I'm here to help you make the most out of our library!

**Comment by novanda1** [comment]
#7
